version: '3'

services:
  database:
    image: mongo:6.0.2
    ports:
      - '27017:27017'
    container_name: database
    environment:
      MONGODB_DATABASE: todo-mongodb
    volumes:
      - ./datase:/data/db
  nestserver: 
    build: ./
    container_name: nest_todo_c
    ports:
      - '${PORT}:3500'
    depends_on:
      - database
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=${PORT}
volumes:
  database: