version: '3'

services:
  database:
    image: mongo:6.0.2
    ports:
      - '27017:27017'
    container_name: database
    environment:
      MONGODB_DATABASE: todo-mongodb
    volumes:
      - ./database:/data/db
volumes:
  database: